# Generated by Django 3.0 on 2022-06-25 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_pro',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='book',
            name='pid',
        ),
    ]
