# Generated by Django 3.0 on 2022-06-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20220625_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_pro',
            name='pid',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
