# Generated by Django 3.0 on 2022-06-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_add_pro_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pid',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
