# Generated by Django 3.0 on 2022-06-26 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_book_pid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_pro',
            name='pid',
        ),
    ]
