# Generated by Django 3.0 on 2022-06-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_add_pro_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='payment',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
