# Generated by Django 3.0 on 2022-07-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_book_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('file', models.ImageField(upload_to='')),
                ('pram', models.CharField(max_length=100)),
                ('prom', models.CharField(max_length=100)),
                ('pcolor', models.CharField(max_length=100)),
                ('pprice', models.IntegerField()),
            ],
        ),
    ]
