# Generated by Django 3.0 on 2022-07-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='us',
            field=models.EmailField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
