# Generated by Django 3.0 on 2022-07-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_remove_cart_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='us',
            field=models.EmailField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
